language: node_js
install:
- npm install
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: CeN1qN8u0T9UdcfvGBVHkTKIjlwRTAMUKJDGAw8is4/KdacJUWlT+Uk8CTdDpzD2YBvLvmX7pjgdoInOV5WwpC99SW/abimr9N7gYlkf3Po9lSFSDd5lhmNwkbBsXGY6LZVfI4fjwFs2UaJSgCQ2ZEehNQ4FlTwXdj/D+nZeshZvpdHo1NJQbN9Ruz2mWwKizg4nGOmQMrftyXlz6oTNZ1J/DPiPHb92MRhCliMNjt3oNHF9QtSwjGFa4EZisf3QNx2GV01hrFhq1yDWV96evv2DeMvvL6B5NAdIldlH4OsN3I1wEd0cA8UU6N0/ELZWbO0dRHNggRB3Ri8GqWmMrLcImC4cKyuciTd4qnPVYSs+tuH8F2LAmTjMZVVNt8riLXWyFnOo2u+W4Sm+y+F0Lj0T2nIMexheobeC/88AP5Egvp7lUoGfdoXbY5nUDRqJcM5/XBv5B2kUUojSmD2iRJYGejaeiOOEgVD8emF2LvY4QPqmZWgYbIjij/Kgi1uDOTDsUPvdHWWS/EIOiLa0TohlzaQQIGVesxp5s4zxxyu2tJu4/YcA5VgL/9HyxAkkywdGbJ/PBWKy8/nHdZ6sd7DOG2xTLVjCfHDAleaTqM+ns9jsQ3xvxYaf3y0mkcT5cB8Yi1vYPAh8izTOlTw+uc5C6qory1wPED3PvccuJag=
